[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "altair>=5.5.0",
    "confluent-kafka>=2.8.2",
    "kafka>=1.3.5",
    "pandas>=2.2.3",
    "streamlit>=1.43.2",
]
