[server]
headless = true
port = 5000
address = "0.0.0.0"
enableCORS = true
enableXsrfProtection = false
enableWebsocketCompression = false
runOnSave = false
maxUploadSize = 10

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 5000

[client]
showErrorDetails = true
toolbarMode = "minimal"
